plugins:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  DisplayStyleGuide: true
  DisplayCopNames: true
  Exclude:
  - vendor/**/*
  - tmp/**/*
  - bin/**/*

inherit_from:
  - ./rubocop/rubocop-layout.yml
  - ./rubocop/rubocop-styles.yml
  - ./rubocop/rubocop-lint.yml
  - ./rubocop/rubocop-metric.yml
  - ./rubocop/rubocop-naming.yml
  - ./rubocop/rubocop-performance.yml
  - ./rubocop/rubocop-rspec.yml
